if(NOT WIN32)
    string(ASCII 27 Esc)
    set(ColorReset  "${Esc}[m")
    set(ColorBold   "${Esc}[1m")
    set(Red         "${Esc}[31m")
    set(Green       "${Esc}[32m")
    set(Yellow      "${Esc}[33m")
    set(Blue        "${Esc}[34m")
    set(Magenta     "${Esc}[35m")
    set(Cyan        "${Esc}[36m")
    set(White       "${Esc}[37m")
    set(BoldRed     "${Esc}[1;31m")
    set(BoldGreen   "${Esc}[1;32m")
    set(BoldYellow  "${Esc}[1;33m")
    set(BoldBlue    "${Esc}[1;34m")
    set(BoldMagenta "${Esc}[1;35m")
    set(BoldCyan    "${Esc}[1;36m")
    set(BoldWhite   "${Esc}[1;37m")

    set(UnderlineRed     "${Esc}[4;31m")
    set(UnderlineGreen   "${Esc}[4;32m")
    set(UnderlineYellow  "${Esc}[4;33m")
    set(UnderlineBlue    "${Esc}[4;34m")
    set(UnderlineMagenta "${Esc}[4;35m")
    set(UnderlineCyan    "${Esc}[4;36m")
    set(UnderlineWhite   "${Esc}[4;37m")

    set(BoldUnderlineRed     "${Esc}[1;4;31m")
    set(BoldUnderlineGreen   "${Esc}[1;4;32m")
    set(BoldUnderlineYellow  "${Esc}[1;4;33m")
    set(BoldUnderlineBlue    "${Esc}[1;4;34m")
    set(BoldUnderlineMagenta "${Esc}[1;4;35m")
    set(BoldUnderlineCyan    "${Esc}[1;4;36m")
    set(BoldUnderlineWhite   "${Esc}[1;4;37m")
endif()
